name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    strategy:
      matrix:
        python-version: [3.12, 3.13]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - uses: pre-commit/action@v3.0.1
