name: Validate rates file
on:
  push:
    paths:
      - rates.yaml
  pull_request:
    paths:
      - rates.yaml

jobs:
  validate-rates-file:
    strategy:
      matrix:
        python-version: [3.12, 3.13]
    name: Validate rates file
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -e .

      - name: Validate rates file
        run: |
          validate-rates-file -g rates.yaml
